spring:
  application:
    name: bookingKol
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - https://www.googleapis.com/auth/calendar
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

app:
  jwtSecretKey: ${JWT_SECRET_KEY}
  jwtExpirationMs: ${JWT_EXPIRATION_MS}